const base="http://127.0.0.1:9222";
const list=await (await fetch(base+"/json")).json();
const page=list.find(t=>t.type==="page");
const ws=new WebSocket(page.webSocketDebuggerUrl);
let id=0; const wait=new Map();
const call=(m,p)=>new Promise(r=>{const i=++id;wait.set(i,r);ws.send(JSON.stringify({id:i,method:m,params:p}));});
ws.onmessage=e=>{const m=JSON.parse(e.data); if(m.id&&wait.has(m.id)){wait.get(m.id)(m);wait.delete(m.id);}};
await new Promise(r=>ws.onopen=r);
await call("Network.setCacheDisabled",{cacheDisabled:true});
await call("Emulation.setDeviceMetricsOverride",{width:660,height:420,deviceScaleFactor:1,mobile:false});
await call("Page.navigate",{url:"http://127.0.0.1:8765/game/_r.html"});
await new Promise(r=>setTimeout(r,2500));
const shot=await call("Page.captureScreenshot",{format:"png"});
const {writeFileSync}=await import("node:fs");
writeFileSync("_r.png", Buffer.from(shot.result.data,"base64"));
console.log("  → _r.png");
process.exit(0);
