# emojis.gd —— emoji 语义注册表(镜像后端 citysim/emojis.py)。
#
# AUTO-GENERATED by tools/gen_emoji_registry.py — 勿手改。
# 新增/调整: 编辑 tools/gen_emoji_registry.py 的 SEMANTIC 表后重新生成。
class_name Emojis
extends RefCounted

const EMOJI := {
	"bed": "🛏️",
	"box": "📦",
	"cart": "🛒",
	"food": "🍱",
	"meal": "🍽️",
	"relaxed": "😌",
	"toilet": "🚽",
	"tool": "🔧",
	"tv": "📺",
	"walk": "🚶",
	"water": "🚰",
}


static func get_icon(key: String, fallback: String = "•") -> String:
	return EMOJI.get(key, fallback)
