"""AUTO-GENERATED by tools/gen_emoji_registry.py — 勿手改。

emoji 单一真源注册表(取自 emojis_by_category/*.json)。
新增/调整: 编辑 tools/gen_emoji_registry.py 的 SEMANTIC 表后重新生成。
"""

SEMANTIC_EMOJI: dict[str, str] = {
    'bed': '🛏️',
    'box': '📦',
    'cart': '🛒',
    'food': '🍱',
    'meal': '🍽️',
    'relaxed': '😌',
    'toilet': '🚽',
    'tool': '🔧',
    'tv': '📺',
    'walk': '🚶',
    'water': '🚰',
}
