// AUTO-GENERATED by tools/gen_emoji_registry.py — 勿手改。
// emoji 单一真源注册表(取自 emojis_by_category/*.json)。

export const EMOJI: Record<string, string> = {
  bed: '🛏️',
  box: '📦',
  cart: '🛒',
  food: '🍱',
  meal: '🍽️',
  relaxed: '😌',
  toilet: '🚽',
  tool: '🔧',
  tv: '📺',
  walk: '🚶',
  water: '🚰',
} as const;
