"""生成 emoji 单一真源注册表(从 emojis_by_category/*.json 取字形)。

用法:
    python tools/gen_emoji_registry.py

产出(勿手改, 均为自动生成):
    src/citysim/emojis.py    -> SEMANTIC_EMOJI: 语义 key -> emoji
    frontend/src/emojis.ts   -> EMOJI:          语义 key -> emoji

新增/调整项目 emoji: 只改下方 SEMANTIC 表(语义 key -> 库内规范英文名),
再重跑本脚本即可; 若 key 指向的名字在库中缺失会报错, 防止用到库外字形。
"""
from __future__ import annotations

import glob
import json
import os
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LIB_DIR = os.path.join(ROOT, "emojis_by_category")

OUT_PY = os.path.join(ROOT, "src", "citysim", "emojis.py")
OUT_TS = os.path.join(ROOT, "frontend", "src", "emojis.ts")

# ---------------------------------------------------------------------------
# 项目语义 key -> emojis_by_category 里的规范英文名(唯一真源, 改这里即可)
# ---------------------------------------------------------------------------
SEMANTIC: dict[str, str] = {
    # ---- 物品/实体图标(snapshot) ----
    "bed": "bed",                    # sleepable 床
    "toilet": "toilet",              # toilet 马桶
    "food": "bento box",             # edible 食物
    "tv": "television",              # entertain 电视
    "water": "potable water",        # drink 饮水
    "meal": "fork and knife with plate",  # consumable 餐食
    "box": "package",                # 其它物品默认
    # ---- 动作图标(explain) ----
    "walk": "person walking",        # move_to 前往
    "cart": "shopping cart",         # buy 购买
    "tool": "wrench",                # interact 使用
    "relaxed": "relieved face",      # idle 闲逛
}


def load_library() -> dict[str, list[str]]:
    """name -> [emoji…]; 同名多字形时全部收集, 生成时取 fully-qualified 版本。"""
    name_to_emojis: dict[str, list[str]] = defaultdict(list)
    for f in sorted(glob.glob(os.path.join(LIB_DIR, "*.json"))):
        if os.path.basename(f) == "index.json":
            continue
        with open(f, encoding="utf-8") as fh:
            data = json.load(fh)
        for e in data.get("emojis", []):
            name_to_emojis[e["name"]].append(e["emoji"])
    return name_to_emojis


def resolve() -> dict[str, str]:
    lib = load_library()
    resolved: dict[str, str] = {}
    errors: list[str] = []
    for key, name in SEMANTIC.items():
        cands = lib.get(name)
        if not cands:
            errors.append(f"key={key!r}: 库中找不到规范名 {name!r}")
            continue
        # 同名多字形: 优先 fully-qualified(带 \uFE0F, 码点更长), 保证渲染一致
        glyph = max(set(cands), key=lambda s: (len(s), s))
        resolved[key] = glyph
    if errors:
        raise SystemExit("\n".join(errors))
    return resolved


def render_py(resolved: dict[str, str]) -> str:
    lines = [
        '"""AUTO-GENERATED by tools/gen_emoji_registry.py — 勿手改。',
        "",
        "emoji 单一真源注册表(取自 emojis_by_category/*.json)。",
        "新增/调整: 编辑 tools/gen_emoji_registry.py 的 SEMANTIC 表后重新生成。",
        '"""',
        "",
        "SEMANTIC_EMOJI: dict[str, str] = {",
    ]
    for k in sorted(resolved):
        lines.append(f"    {k!r}: {resolved[k]!r},")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_ts(resolved: dict[str, str]) -> str:
    lines = [
        "// AUTO-GENERATED by tools/gen_emoji_registry.py — 勿手改。",
        "// emoji 单一真源注册表(取自 emojis_by_category/*.json)。",
        "",
        "export const EMOJI: Record<string, string> = {",
    ]
    for k in sorted(resolved):
        lines.append(f"  {k}: '{resolved[k]}',")
    lines.append("} as const;")
    return "\n".join(lines) + "\n"


def main() -> None:
    resolved = resolve()
    for path, text in ((OUT_PY, render_py(resolved)), (OUT_TS, render_ts(resolved))):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print(f"written: {path}  ({len(resolved)} keys)")


if __name__ == "__main__":
    main()
